/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Consultas.ConsultasAspirantes;
import Consultas.ConsultasEmpleo;
import Consultas.ConsultasEmpresa;
import Consultas.ConsultasGiroComercial;
import Entidades.Empleo;
import Entidades.Empresa;
import Entidades.GiroComercial;
import Entidades.cargar_Aspirantes;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eli_Ingeniero
 */
public class FrmP_Empresa1 extends javax.swing.JFrame {

    ConsultasEmpresa AE = new ConsultasEmpresa();
    ConsultasEmpleo AC = new ConsultasEmpleo();

    /**
     * Creates new form Frm_Empresa
     */
    public FrmP_Empresa1() {
        initComponents();
        btnActualizar.setVisible(false);
        txtId.setVisible(false);
        txturl2.setVisible(false);
        lblidempresa.setVisible(false);
        idgiro.setVisible(false);
        txtDescripciones.setLineWrap(true);
        txtRequisitos.setLineWrap(true);
        this.setBounds(0, 0, 1400, 900);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jc_girocomercial.setVisible(false);
        actualizargiro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empresa = new javax.swing.JPanel();
        titulos = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnperfil = new javax.swing.JButton();
        btnGestionarEmpleos = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPaneEmpresa = new javax.swing.JScrollPane();
        jp_todo = new javax.swing.JPanel();
        jPanelSliderEmpresa = new diu.swe.habib.JPanelSlider.JPanelSlider();
        inicio = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lb_fotoEmpresas1 = new javax.swing.JLabel();
        btnCambiarFoto = new javax.swing.JButton();
        txturl2 = new javax.swing.JTextField();
        jp_generalidadesEmpresa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbn_ubicacion = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtDepartamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAcronimo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        idgiro = new javax.swing.JTextField();
        lblidempresa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtgirocomercial = new javax.swing.JTextField();
        jc_girocomercial = new javax.swing.JComboBox();
        jpGestiones = new javax.swing.JPanel();
        btnGestionar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        Gestionar_Empleos = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Empleos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_empleos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtEmpleo = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescripciones = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtRequisitos = new javax.swing.JTextArea();
        empleo = new javax.swing.JLabel();
        salario = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        requisitos = new javax.swing.JLabel();
        guardarEmpleo = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        nuevoempleo = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        aspirantes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_aspirantes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        idtrabajador = new javax.swing.JLabel();
        btncargarperfil = new javax.swing.JButton();
        nombre_trabajador = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtempleo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulos.setBackground(new java.awt.Color(102, 0, 102));

        logo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo3.0.png"))); // NOI18N
        logo.setText("Work Search Engine. ");
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnperfil.setBackground(new java.awt.Color(153, 0, 153));
        btnperfil.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnperfil.setForeground(new java.awt.Color(255, 255, 255));
        btnperfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        btnperfil.setText("    Perfil");
        btnperfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnperfil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperfilActionPerformed(evt);
            }
        });

        btnGestionarEmpleos.setBackground(new java.awt.Color(153, 0, 153));
        btnGestionarEmpleos.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        btnGestionarEmpleos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarEmpleos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bell.png"))); // NOI18N
        btnGestionarEmpleos.setText("Gestionar Empleos");
        btnGestionarEmpleos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEmpleosActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_24.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titulosLayout = new javax.swing.GroupLayout(titulos);
        titulos.setLayout(titulosLayout);
        titulosLayout.setHorizontalGroup(
            titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(213, 213, 213)
                .addComponent(btnperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnGestionarEmpleos)
                .addGap(355, 355, 355)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        titulosLayout.setVerticalGroup(
            titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titulosLayout.createSequentialGroup()
                .addGroup(titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logo)
                        .addComponent(btnperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGestionarEmpleos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titulosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnsalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_fotoEmpresas1.setBackground(new java.awt.Color(51, 51, 255));
        lb_fotoEmpresas1.setForeground(new java.awt.Color(51, 51, 255));
        lb_fotoEmpresas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_fotoEmpresas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/folder de trabajo.png"))); // NOI18N
        lb_fotoEmpresas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_fotoEmpresas1MouseClicked(evt);
            }
        });
        jPanel4.add(lb_fotoEmpresas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 140));

        btnCambiarFoto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCambiarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/añadirfoto_64.png"))); // NOI18N
        btnCambiarFoto.setText("Cambiar Foto");
        btnCambiarFoto.setBorder(null);
        btnCambiarFoto.setContentAreaFilled(false);
        btnCambiarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCambiarFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiarFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCambiarFoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCambiarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarFotoActionPerformed(evt);
            }
        });
        jPanel4.add(btnCambiarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, -1));

        txturl2.setText("jTextField1");
        txturl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txturl2ActionPerformed(evt);
            }
        });
        jPanel4.add(txturl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jp_generalidadesEmpresa.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 99, 66));
        jLabel2.setText("Direccion de  empresa ");

        jbn_ubicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_location_on_128_28437.png"))); // NOI18N
        jbn_ubicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbn_ubicacionMouseClicked(evt);
            }
        });
        jbn_ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbn_ubicacionActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);
        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(39, 86, 179));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GMail_icon-icons.com_76886.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 99, 66));
        jLabel3.setText("Correo electronico ");

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(39, 86, 179));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 99, 66));
        jLabel4.setText("Telefono ");

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(39, 86, 179));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/phone_icon-icons.com_48251.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_attach_money_128_28210.png"))); // NOI18N

        txtDepartamento.setEditable(false);
        txtDepartamento.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDepartamento.setForeground(new java.awt.Color(39, 86, 179));
        txtDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartamentoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 99, 66));
        jLabel5.setText("Departamento");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setMaximumSize(new java.awt.Dimension(168, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(168, 24));

        txtAcronimo.setEditable(false);
        txtAcronimo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtAcronimo.setForeground(new java.awt.Color(39, 86, 179));
        txtAcronimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(39, 86, 179));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 99, 66));
        jLabel6.setText("Contraseña...");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 99, 66));
        jLabel7.setText("Giro Comercial");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empresa_32.png"))); // NOI18N

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bloquear_24.png"))); // NOI18N

        txtContraseña.setEditable(false);
        txtContraseña.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(39, 86, 179));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 99, 66));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Descripcion...");

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(39, 86, 179));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jp_generalidadesEmpresaLayout = new javax.swing.GroupLayout(jp_generalidadesEmpresa);
        jp_generalidadesEmpresa.setLayout(jp_generalidadesEmpresaLayout);
        jp_generalidadesEmpresaLayout.setHorizontalGroup(
            jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbn_ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                                .addComponent(txtDireccion)
                                                .addGap(262, 262, 262)))
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgirocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(46, 46, 46)
                                .addComponent(idgiro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(txtAcronimo, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jc_girocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblidempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_generalidadesEmpresaLayout.setVerticalGroup(
            jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addComponent(txtAcronimo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addComponent(jc_girocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbn_ubicacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))
                            .addComponent(txtgirocomercial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_generalidadesEmpresaLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jp_generalidadesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idgiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblidempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jpGestiones.setBackground(new java.awt.Color(102, 0, 102));
        jpGestiones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGestionar.setBackground(new java.awt.Color(153, 255, 153));
        btnGestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/settings24.png"))); // NOI18N
        btnGestionar.setText("Gestionar...");
        btnGestionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionarMouseClicked(evt);
            }
        });
        btnGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActionPerformed(evt);
            }
        });
        jpGestiones.add(btnGestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 151, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SSuccess.png"))); // NOI18N
        btnActualizar.setText("Actualizar ");
        btnActualizar.setBorder(null);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NNSuccess.png"))); // NOI18N
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jpGestiones.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 63));

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_generalidadesEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpGestiones, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_generalidadesEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addComponent(jpGestiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSliderEmpresa.add(inicio, "card2");

        tabla_empleos.setAutoCreateRowSorter(true);
        tabla_empleos.setBackground(new java.awt.Color(153, 0, 255));
        tabla_empleos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_empleos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_empleosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_empleos);

        jPanel3.setBackground(new java.awt.Color(202, 219, 236));

        txtDescripciones.setColumns(20);
        txtDescripciones.setRows(5);
        jScrollPane6.setViewportView(txtDescripciones);

        txtRequisitos.setColumns(20);
        txtRequisitos.setRows(5);
        jScrollPane7.setViewportView(txtRequisitos);

        empleo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        empleo.setForeground(new java.awt.Color(26, 99, 66));
        empleo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empleo.setText("Empleo");

        salario.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        salario.setForeground(new java.awt.Color(26, 99, 66));
        salario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salario.setText("salario");

        descripcion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(26, 99, 66));
        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descripcion.setText("Descripciones");

        requisitos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        requisitos.setForeground(new java.awt.Color(26, 99, 66));
        requisitos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requisitos.setText("Requisitos");

        guardarEmpleo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        guardarEmpleo.setForeground(new java.awt.Color(39, 86, 179));
        guardarEmpleo.setText("Guardar");
        guardarEmpleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEmpleoActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);

        nuevoempleo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nuevoempleo.setForeground(new java.awt.Color(0, 51, 153));
        nuevoempleo.setText("nuevo");
        nuevoempleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoempleoActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(0, 0, 102));
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empleo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpleo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(requisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoempleo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardarEmpleo)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarEmpleo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoempleo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion)
                            .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empleo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmpleo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EmpleosLayout = new javax.swing.GroupLayout(Empleos);
        Empleos.setLayout(EmpleosLayout);
        EmpleosLayout.setHorizontalGroup(
            EmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleosLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(EmpleosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmpleosLayout.setVerticalGroup(
            EmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("lista de empleos", Empleos);

        tabla_aspirantes.setBackground(new java.awt.Color(153, 0, 204));
        tabla_aspirantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_aspirantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_aspirantesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_aspirantes);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btncargarperfil.setText("perfil");

        nombre_trabajador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_trabajadorActionPerformed(evt);
            }
        });

        txtapellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        txtempleo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtempleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempleoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nombre_trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idtrabajador)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btncargarperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtempleo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idtrabajador)
                .addGap(177, 177, 177)
                .addComponent(txtempleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_trabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btncargarperfil)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aspirantesLayout = new javax.swing.GroupLayout(aspirantes);
        aspirantes.setLayout(aspirantesLayout);
        aspirantesLayout.setHorizontalGroup(
            aspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aspirantesLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        aspirantesLayout.setVerticalGroup(
            aspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aspirantesLayout.createSequentialGroup()
                .addGroup(aspirantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(aspirantesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("lista de aspirantes ", aspirantes);

        javax.swing.GroupLayout Gestionar_EmpleosLayout = new javax.swing.GroupLayout(Gestionar_Empleos);
        Gestionar_Empleos.setLayout(Gestionar_EmpleosLayout);
        Gestionar_EmpleosLayout.setHorizontalGroup(
            Gestionar_EmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gestionar_EmpleosLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Gestionar_EmpleosLayout.setVerticalGroup(
            Gestionar_EmpleosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Gestionar_EmpleosLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jPanelSliderEmpresa.add(Gestionar_Empleos, "card4");

        javax.swing.GroupLayout jp_todoLayout = new javax.swing.GroupLayout(jp_todo);
        jp_todo.setLayout(jp_todoLayout);
        jp_todoLayout.setHorizontalGroup(
            jp_todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_todoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSliderEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_todoLayout.setVerticalGroup(
            jp_todoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSliderEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPaneEmpresa.setViewportView(jp_todo);

        javax.swing.GroupLayout empresaLayout = new javax.swing.GroupLayout(empresa);
        empresa.setLayout(empresaLayout);
        empresaLayout.setHorizontalGroup(
            empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empresaLayout.createSequentialGroup()
                .addComponent(titulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addComponent(jScrollPaneEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        empresaLayout.setVerticalGroup(
            empresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    String filasCombo[] = new String[13];
    
    String array[] = new String[23];
    int contadors = 0;
    
    public void actualizargiro() {
        ConsultasGiroComercial mo = new ConsultasGiroComercial();
        ArrayList<GiroComercial> PS = mo.mostrargiros();
        Iterator i = PS.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        while (i.hasNext()) {
            GiroComercial p;
            p = (GiroComercial) i.next();
            array[contadors] = String.valueOf(p.getIdGiroComercial());
            filasCombo[1] = p.getCategoriaNombre();
            DefaultComboBoxModel.addElement(p.getCategoriaNombre());
            contadors++;
        }
        
        jc_girocomercial.setModel(DefaultComboBoxModel);
    }
    
    void cargarTabla() {
        String titulos[] = {"Id", "Empleo", "Descripcion", "Requisitos", "Salario"};
        DefaultTableModel df = new DefaultTableModel(null, titulos);
        ConsultasEmpleo mo = new ConsultasEmpleo();
        ArrayList<Empleo> PS = mo.Mostraempleos();
        Iterator i = PS.iterator();
        String filas[] = new String[5];
        while (i.hasNext()) {
            Empleo p;
            
            p = (Empleo) i.next();
            
            int id = p.getIdEmpleo();
            filas[0] = String.valueOf(id);
            filas[1] = p.getNombre();
            filas[2] = p.getDescripcion();
            filas[3] = p.getRequisitos();
            double salario = p.getSalario();
            filas[4] = String.valueOf(salario);
            
            df.addRow(filas);
        }
        tabla_empleos.setModel(df);
        
    }
    
    void cargarTablaaspirantes() {
        String titulos[] = {"id", "Nombre", "Apellidos", "Empleo", "Requisitos de Empleo"};
        DefaultTableModel df = new DefaultTableModel(null, titulos);
        ConsultasEmpresa mo = new ConsultasEmpresa();
        ArrayList<cargar_Aspirantes> PS = mo.MostraAspirantes();
        Iterator i = PS.iterator();
        String filas[] = new String[5];
        while (i.hasNext()) {
            cargar_Aspirantes a;
            
            a = (cargar_Aspirantes) i.next();
            int idtrabajador = a.getIdTrabajador();
            filas[0] = String.valueOf(idtrabajador);
            filas[1] = a.getNombreT();
            filas[2] = a.getApellidoT();
            filas[4] = a.getRequisitosE();
            filas[3] = a.getNombreE();
            df.addRow(filas);
        }
        tabla_aspirantes.setModel(df);
        
    }

    private void btnperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperfilActionPerformed
        if (!btnperfil.isSelected()) {
            btnperfil.setSelected(true);
            
            btnGestionarEmpleos.setSelected(false);
            
            jPanelSliderEmpresa.nextPanel(10, inicio, jPanelSliderEmpresa.left);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnperfilActionPerformed

    private void btnGestionarEmpleosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEmpleosActionPerformed
        cargarTabla();
        cargarTablaaspirantes();
        if (!btnGestionarEmpleos.isSelected()) {
            btnGestionarEmpleos.setSelected(true);
            
            btnperfil.setSelected(false);
            jPanelSliderEmpresa.nextPanel(10, Gestionar_Empleos, jPanelSliderEmpresa.left);
        }
    }//GEN-LAST:event_btnGestionarEmpleosActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void tabla_empleosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_empleosMouseClicked
        
        String id, empleo, salario, descripcion, requisitos;
        
        id = String.valueOf(tabla_empleos.getModel().getValueAt(tabla_empleos.getSelectedRow(), 0));
        empleo = String.valueOf(tabla_empleos.getModel().getValueAt(tabla_empleos.getSelectedRow(), 1));
        
        descripcion = String.valueOf(tabla_empleos.getModel().getValueAt(tabla_empleos.getSelectedRow(), 2));
        requisitos = String.valueOf(tabla_empleos.getModel().getValueAt(tabla_empleos.getSelectedRow(), 3));
        salario = String.valueOf(tabla_empleos.getModel().getValueAt(tabla_empleos.getSelectedRow(), 4));
        txtId.setText(id);
        txtEmpleo.setText(empleo);
        txtSalario.setText(salario);
        txtDescripciones.setText(descripcion);
        txtRequisitos.setText(requisitos);
        

    }//GEN-LAST:event_tabla_empleosMouseClicked

    private void guardarEmpleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEmpleoActionPerformed
        
        Empleo e = new Empleo();
        
        e.setIdEmpleo(Integer.parseInt(txtId.getText()));
        e.setNombre(txtEmpleo.getText());
        e.setRequisitos(txtRequisitos.getText());
        e.setDescripcion(txtDescripciones.getText());
        e.setSalario(Double.parseDouble(txtSalario.getText()));
        
        AC.Actualizarempleo(e);
        cargarTabla();
        
        txtEmpleo.setText(" ");
        txtSalario.setText(" ");
        txtDescripciones.setText(" ");
        txtRequisitos.setText(" ");        

    }//GEN-LAST:event_guardarEmpleoActionPerformed
    File file;
    private void btnCambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarFotoActionPerformed
        Empresa es = new Empresa();
        try {
            es.setIdEmpresa(Integer.parseInt(lblidempresa.getText()));
            byte[] sq = Files.readAllBytes(file.toPath());
            es.setImPerfil(sq);
            
            ConsultasEmpresa actualizar = new ConsultasEmpresa();            
            actualizar.actualizar_empresafoto(es);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnCambiarFotoActionPerformed

    private void jbn_ubicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbn_ubicacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_ubicacionMouseClicked

    private void jbn_ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbn_ubicacionActionPerformed
        txtDireccion.selectAll();
        
        txtDireccion.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jbn_ubicacionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtCorreo.selectAll();
        txtCorreo.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtTelefono.selectAll();
        txtTelefono.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartamentoActionPerformed

    private void btnGestionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarMouseClicked
        
        txtContraseña.setVisible(true);

    }//GEN-LAST:event_btnGestionarMouseClicked

    private void btnGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActionPerformed
        txtgirocomercial.setVisible(false);
        jc_girocomercial.setVisible(true);
        actualizargiro();
        btnActualizar.setVisible(true);
        txtNombre.setEditable(true);
        txtAcronimo.setEditable(true);
        txtDireccion.setEditable(true);
        txtCorreo.setEditable(true);
        txtTelefono.setEditable(true);
        
        txtDepartamento.setEditable(true);
        txtContraseña.setEditable(true);
        txtDescripcion.setEditable(true);

    }//GEN-LAST:event_btnGestionarActionPerformed
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //AC=actualizar empresa

        try {
            
            Empresa et = new Empresa();
            et.setIdEmpresa(Integer.parseInt(lblidempresa.getText()));
            et.setNombre(txtNombre.getText());
            et.setAcronimo(txtAcronimo.getText());
            et.setDescripcion(txtDescripcion.getText());
            et.setDepartamento(txtDepartamento.getText());
            et.setDireccion(txtDireccion.getText());
            et.setTelefono(txtTelefono.getText());
            et.setCorreo(txtCorreo.getText());
            et.setContraseña(txtContraseña.getText());
            int indice, otro;
            String valor;
            indice = jc_girocomercial.getSelectedIndex();
            valor = array[indice];
            otro = Integer.parseInt(valor);
            et.setIdGiroComercial(otro);
            
            AE.Actualizar_empresa(et);
            
            btnActualizar.setVisible(false);
            txtgirocomercial.setVisible(true);
            jc_girocomercial.setVisible(false);
            
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void nuevoempleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoempleoActionPerformed
        txtEmpleo.setText(" ");
        txtSalario.setText(" ");
        txtDescripciones.setText(" ");
        txtRequisitos.setText(" ");        
        cargarTabla();// TODO add your handling code here:
    }//GEN-LAST:event_nuevoempleoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        
        Empleo e = new Empleo();
        e.setIdEmpleo(Integer.parseInt(txtId.getText()));
        e.setNombre(txtEmpleo.getText());
        e.setRequisitos(txtRequisitos.getText());
        e.setDescripcion(txtDescripcion.getText());
        e.setSalario(Double.parseDouble(txtSalario.getText()));
        AC.Actualizarempleo(e);
        cargarTabla();
        txtEmpleo.setText(" ");
        txtSalario.setText(" ");
        txtDescripciones.setText(" ");
        txtRequisitos.setText(" ");        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void lb_fotoEmpresas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_fotoEmpresas1MouseClicked
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "jpg", "png", "jpeg");
        archivo.setFileFilter(filtro);
        archivo.setDialogTitle("Elegir Imagen de Perfil");
        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            file = archivo.getSelectedFile();
            txturl2.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(txturl2.getText());
            foto = foto.getScaledInstance(lb_fotoEmpresas1.getWidth(), lb_fotoEmpresas1.getHeight(), Image.SCALE_DEFAULT);
            
            lb_fotoEmpresas1.setIcon(new ImageIcon(foto));
        }// TODO add your handling code here:
    }//GEN-LAST:event_lb_fotoEmpresas1MouseClicked

    private void txturl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txturl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txturl2ActionPerformed

    private void tabla_aspirantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_aspirantesMouseClicked
        String id, Nombre, Apellidos, Empleo, Requisitos_Empleo;
        id = String.valueOf(tabla_aspirantes.getModel().getValueAt(tabla_aspirantes.getSelectedRow(), 0));
        Nombre = String.valueOf(tabla_aspirantes.getModel().getValueAt(tabla_aspirantes.getSelectedRow(), 1));
        
        Apellidos = String.valueOf(tabla_aspirantes.getModel().getValueAt(tabla_aspirantes.getSelectedRow(), 2));
        Empleo = String.valueOf(tabla_aspirantes.getModel().getValueAt(tabla_aspirantes.getSelectedRow(), 3));
        Requisitos_Empleo = String.valueOf(tabla_aspirantes.getModel().getValueAt(tabla_aspirantes.getSelectedRow(), 4));
        idtrabajador.setText(id);
        nombre_trabajador.setText(Nombre);
        txtapellido.setText(Apellidos);
        txtempleo.setText(Empleo);

    }//GEN-LAST:event_tabla_aspirantesMouseClicked

    private void nombre_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_trabajadorActionPerformed
        nombre_trabajador.setEditable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_trabajadorActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtempleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempleoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempleoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmP_Empresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmP_Empresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmP_Empresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmP_Empresa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmP_Empresa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Empleos;
    private javax.swing.JPanel Gestionar_Empleos;
    private javax.swing.JPanel aspirantes;
    private javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCambiarFoto;
    private javax.swing.JButton btnGestionar;
    private javax.swing.JButton btnGestionarEmpleos;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncargarperfil;
    private javax.swing.JButton btnperfil;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel empleo;
    private javax.swing.JPanel empresa;
    private javax.swing.JButton guardarEmpleo;
    public javax.swing.JTextField idgiro;
    public javax.swing.JLabel idtrabajador;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSliderEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPaneEmpresa;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbn_ubicacion;
    public javax.swing.JComboBox jc_girocomercial;
    private javax.swing.JPanel jpGestiones;
    private javax.swing.JPanel jp_generalidadesEmpresa;
    private javax.swing.JPanel jp_todo;
    public javax.swing.JLabel lb_fotoEmpresas1;
    public javax.swing.JTextField lblidempresa;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombre_trabajador;
    private javax.swing.JButton nuevoempleo;
    private javax.swing.JLabel requisitos;
    private javax.swing.JLabel salario;
    public javax.swing.JTable tabla_aspirantes;
    public javax.swing.JTable tabla_empleos;
    private javax.swing.JPanel titulos;
    public javax.swing.JTextField txtAcronimo;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDepartamento;
    public javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripciones;
    public javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmpleo;
    private javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtRequisitos;
    private javax.swing.JTextField txtSalario;
    public javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtempleo;
    public javax.swing.JTextField txtgirocomercial;
    private javax.swing.JTextField txturl2;
    // End of variables declaration//GEN-END:variables
}
